function Jv = auto_Jv(in1)
%auto_Jv
%    Jv = auto_Jv(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    28-Feb-2026 03:23:27

theta1 = in1(1,:);
theta2 = in1(2,:);
theta3 = in1(3,:);
theta4 = in1(4,:);
t2 = cos(theta1);
t3 = cos(theta2);
t4 = sin(theta1);
t5 = sin(theta2);
t6 = theta2+theta3;
t7 = t3.*5.0;
t8 = t5.*5.0;
t9 = cos(t6);
t10 = sin(t6);
t11 = t6+theta4;
t12 = cos(t11);
t13 = sin(t11);
t14 = t9.*3.0;
t15 = t10.*3.0;
t16 = t9.*3.0e+1;
t17 = t12.*1.0e+1;
t18 = t13+t15;
t19 = t7+t12+t14;
t20 = t8+t18;
Jv = reshape([t4.*t19.*-1.0e+1,t2.*t19.*1.0e+1,0.0,t2.*t20.*-1.0e+1,t4.*t20.*-1.0e+1,t3.*5.0e+1+t16+t17,t2.*t18.*-1.0e+1,t4.*t18.*-1.0e+1,t16+t17,t2.*t13.*-1.0e+1,t4.*t13.*-1.0e+1,t17],[3,4]);
end
