function pe = auto_Fk(in1)
%auto_Fk
%    PE = auto_Fk(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    28-Feb-2026 03:23:27

theta1 = in1(1,:);
theta2 = in1(2,:);
theta3 = in1(3,:);
theta4 = in1(4,:);
t2 = cos(theta2);
t3 = theta2+theta3;
t4 = t2.*5.0;
t5 = cos(t3);
t6 = t3+theta4;
t7 = cos(t6);
t8 = t5.*3.0;
t9 = t4+t7+t8;
pe = [t9.*cos(theta1).*1.0e+1;t9.*sin(theta1).*1.0e+1;sin(t3).*3.0e+1+sin(t6).*1.0e+1+sin(theta2).*5.0e+1+1.0e+1];
end
