function f = auto_f(in1,in2)
%AUTO_F
%    F = AUTO_F(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    28-Feb-2026 03:23:28

qk1 = in1(1,:);
qk2 = in1(2,:);
qk3 = in1(3,:);
qk4 = in1(4,:);
vd1 = in2(1,:);
vd2 = in2(2,:);
vd3 = in2(3,:);
t2 = cos(qk1);
t3 = cos(qk2);
t4 = sin(qk1);
t5 = sin(qk2);
t6 = qk2+qk3;
t7 = t5.*5.0;
t8 = cos(t6);
t9 = qk4+t6;
t10 = sin(t6);
t11 = cos(t9);
t12 = sin(t9);
t13 = t10.*3.0;
t14 = t8.*6.0e+1;
t15 = t11.*2.0e+1;
t16 = t12+t13;
t17 = t7+t16;
f = [(t2.*vd2-t4.*vd1).*(t3.*5.0+t8.*3.0+t11).*-2.0e+1;-vd3.*(t3.*1.0e+2+t14+t15)+t2.*t17.*vd1.*2.0e+1+t4.*t17.*vd2.*2.0e+1;-vd3.*(t14+t15)+t2.*t16.*vd1.*2.0e+1+t4.*t16.*vd2.*2.0e+1;t11.*vd3.*-2.0e+1+t2.*t12.*vd1.*2.0e+1+t4.*t12.*vd2.*2.0e+1];
end
