function A = auto_A(in1)
%auto_A
%    A = auto_A(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    08-Feb-2026 15:00:36

qk1 = in1(1,:);
qk2 = in1(2,:);
qk3 = in1(3,:);
qk4 = in1(4,:);
A = reshape([qk1,qk2,qk3,qk4,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0./1.0e+1,0.0,0.0,0.0,0.0,1.0./1.0e+1,0.0,0.0,0.0,0.0,1.0./1.0e+1,0.0,0.0,0.0,0.0,1.0./1.0e+1],[4,9]);
end
