function H = auto_H(in1)
%auto_H
%    H = auto_H(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    28-Feb-2026 03:23:28

qk1 = in1(1,:);
qk2 = in1(2,:);
qk3 = in1(3,:);
qk4 = in1(4,:);
t2 = cos(qk2);
t3 = cos(qk3);
t4 = cos(qk4);
t5 = qk2+qk3;
t6 = qk3+qk4;
t7 = t2.*5.0;
t8 = cos(t5);
t9 = cos(t6);
t10 = qk4+t5;
t13 = t4.*6.0e+2;
t14 = t4.*1.2e+3;
t15 = t3.*3.0e+3;
t11 = cos(t10);
t12 = t8.*3.0;
t16 = t9.*1.0e+3;
t17 = t13+2.0e+2;
t18 = t7+t11+t12;
t20 = t16+t17;
t21 = t14+t15+t16+2.0e+3;
t19 = t18.^2;
H = reshape([t19.*cos(qk1).^2.*2.0e+2+t19.*sin(qk1).^2.*2.0e+2+1.0./5.0,0.0,0.0,0.0,0.0,t3.*6.0e+3+t9.*2.0e+3+t14+7.0002e+3,t21,t20,0.0,t21,t14+2.0002e+3,t17,0.0,t20,t17,2.002e+2],[4,4]);
end
